import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider"
import { GeistSans } from "geist/font/sans";
import { GeistMono } from 'geist/font/mono'
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Chronicle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${GeistSans.variable} ${GeistMono.variable}`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
